[package]
name = "glean"
version = "34.1.0"
authors = ["Jan-Erik Rediger <jrediger@mozilla.com>", "The Glean Team <glean-team@mozilla.com>"]
description = "Glean SDK Rust language bindings"
repository = "https://github.com/mozilla/glean"
readme = "README.md"
license = "MPL-2.0"
edition = "2018"
keywords = ["telemetry", "glean"]
include = [
  "/README.md",
  "/LICENSE",
  "/src",
  "/tests",
  "/Cargo.toml",
]

[features]
glean-dynamic = ["glean-ffi-sys", "libloading"]

[badges]
circle-ci = { repository = "mozilla/glean", branch = "main" }
maintenance = { status = "actively-developed" }

[dependencies.glean-core]
path = ".."
version = "34.1.0"

[dependencies.glean-ffi-sys]
path = "../ffi-sys"
version = "0.1.0"
optional = true

[dependencies]
crossbeam-channel = "0.5"
inherent = "0.1.4"
log = "0.4.8"
once_cell = "1.2.0"
thiserror = "1.0.4"
serde_json = "1.0.44"
serde = { version = "1.0.104", features = ["derive"] }
uuid = { version = "0.8.1", features = ["v4"] }
chrono = { version = "0.4.10", features = ["serde"] }
time = "0.1.40"
libloading = { version = "0.6.6", optional = true }

[dev-dependencies]
env_logger = { version = "0.7.1", default-features = false, features = ["termcolor", "atty", "humantime"] }
tempfile = "3.1.0"
jsonschema-valid = "0.4.0"
flate2 = "1.0.19"
