name: install-rustup
runs:
  using: composite
  steps:
  - name: Installing rustup
    run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    shell: bash
  - name: Setup custom environment variables
    run: echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV
    shell: bash