name: install-python-windows-deps
runs:
  using: composite
  steps:
  - name: Set up dependencies for Python for Windows
    run: |-
      echo "export WINEDEBUG=-all" >> $BASH_ENV
      wget https://bootstrap.pypa.io/get-pip.py
      $WINPYTHON get-pip.py
      echo "import site" >> winpython/python38._pth
      echo "import sys; sys.path.insert(0, '')" >> winpython/sitecustomize.py
      # The Windows-Python-installed-inside-Wine thing can't actually build wheels,
      # so just install all of the wheels that were created as part of creating the
      # environment on the host system before attempting to install everything in
      # requirements_dev.txt
      find ~/.cache/pip -name "*.whl" -exec $WINPYTHON -m pip install {} \;
      $WINPYTHON -m pip install -r glean-core/python/requirements_dev.txt --no-warn-script-location
      $WINPYTHON -m pip install target/wheels/*.whl --no-warn-script-location
    shell: bash