name: test-rust
inputs:
  rust-version:
    required: false
    default: stable
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4.1.0
  - uses: "./.github/actions/skip-if-doc-only"
  - uses: "./.github/actions/setup-rust-toolchain"
    with:
      rust-version: "${{ inputs.rust-version }}"
  - name: Install required Python dependencies
    run: |-
      sudo apt update
      sudo apt install --yes --no-install-recommends \
        python3-pip \
        python3.10-venv
    shell: bash
  - name: Install nextest
    run: |-
      NEXTEST_SHA256=bde8d231e435099b068e654c591224defe686c784b4920682ee12784b6bfcf9e
      NEXTEST=cargo-nextest
      curl -sfSL --retry 5 -o "${NEXTEST}.tar.gz" "https://get.nexte.st/0.9.87/linux"
      echo "${NEXTEST_SHA256} *${NEXTEST}.tar.gz" | shasum -a 256 -c -
      tar -xf "${NEXTEST}.tar.gz"
      cp ./${NEXTEST} ~/.cargo/bin/
    shell: bash
  - name: Install circleci-junit-fix
    run: |-
      JUNIT_FIX_SHA256=e8dd9012c841d9c03037783db676aa43a2ac1900346ccf4a61bf9956acfc6032
      JUNIT_FIX=circleci-junit-fix
      JUNIT_FIX_VERSION=v0.2.0
      curl -sfSL --retry 5 -o "${JUNIT_FIX}.tar.gz" "https://github.com/conradludgate/circleci-junit-fix/releases/download/${JUNIT_FIX_VERSION}/${JUNIT_FIX}-${JUNIT_FIX_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
      echo "${JUNIT_FIX_SHA256} *${JUNIT_FIX}.tar.gz" | shasum -a 256 -c -
      tar -xf "${JUNIT_FIX}.tar.gz"
      cp ./${JUNIT_FIX} ~/.cargo/bin/
    shell: bash
  - name: Test
    run: cargo nextest run --profile ci
    shell: bash
  - name: Fix junit output
    run: |-
      mkdir -p ~/test-results/
      cat target/nextest/ci/junit.xml | circleci-junit-fix > ~/test-results/junit.xml
    if: always()
    shell: bash
  - uses: actions/upload-artifact@v4.1.0
    with:
      path: "~/test-results"
  - name: Run Rust sample
    run: cargo run -p sample
    shell: bash
  - name: Run Rust RLB test
    run: glean-core/rlb/tests/test-shutdown-blocking.sh
    shell: bash
  - name: Run Rust RLB crash test
    run: glean-core/rlb/tests/test-thread-crashing.sh
    shell: bash
  - name: Run Rust RLB delayed ping data test
    run: glean-core/rlb/tests/test-delayed-ping-data.sh
    shell: bash
  - name: Run Rust RLB flush test
    run: glean-core/rlb/tests/test-ping-lifetime-flush.sh
    shell: bash
  - name: Run Rust RLB enabled-pings test
    run: glean-core/rlb/tests/test-enabled-pings.sh
    shell: bash
  - name: Run Rust RLB pending-gets-removed test
    run: glean-core/rlb/tests/test-pending-gets-removed.sh
    shell: bash