name: On comment

on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

jobs:
  dispatch-swift:
    if: |
      github.event.issue.pull_request && startsWith(github.event.comment.body, '/run-ios')
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Swift tests
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_NUMBER: ${{ github.event.issue.number }}
          ACTOR: ${{ github.actor }}
          PULL_REQUEST: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          set -x

          permission=$(gh api /repos/badboy/glean/collaborators/${ACTOR}/permission | jq -r .permission)
          if [[ "$permission" = "admin" ]]; then
            true
          else
            echo "Insufficient permission. Stopping."
            exit 0
          fi

          pr_info=$(gh api "/repos/badboy/glean/pulls/${PR_NUMBER}")
          pr_state=$(echo "$pr_info" | jq -r .state)
          if [[ "$pr_state" != "open" ]]; then
            echo "PR is not open. State: ${pr_state}. Stopping."
            exit 0
          fi

          WORKFLOW_URL=$(gh workflow run -R badboy/glean .github/workflows/test-swift.yml -f "pull-request=${PULL_REQUEST}")

          gh issue comment -R badboy/glean "${PR_NUMBER}" -b "iOS test run triggered: ${WORKFLOW_URL}"
          gh api "/repos/badboy/glean/statuses/${PULL_REQUEST}" \
            -f 'state=pending' \
            -f "target_url=${WORKFLOW_URL}" \
            -f 'context=ci/swift2' \
            -f 'description=Build started'
